name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - run: pip install poetry
    - run: poetry install
    - run: poetry run black --check .
    - run: poetry run mypy .
    - run: poetry run pytest
