name: docs

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write    # required for gh-pages push

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"     # ← align

      - name: Install package + docs deps
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install sphinx sphinx-rtd-theme sphinx-autodoc-typehints sphinxcontrib-napoleon

      - name: Build docs
        run: sphinx-build -b html docs docs/_build/html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/_build/html
